/**
 * ApiGateway
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type BooleanThreeStates =
    'NotDefined'
    | 'True'
    | 'False';

export const BooleanThreeStates = {
    NotDefined: 'NotDefined' as BooleanThreeStates,
    True: 'True' as BooleanThreeStates,
    False: 'False' as BooleanThreeStates,
};