/**
 * ApiGateway
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AdvancedPieChartDTO } from './advancedPieChartDTO';
import { AreaChartDTO } from './areaChartDTO';
import { BoxChartDTO } from './boxChartDTO';
import { GaugeChartDTO } from './gaugeChartDTO';
import { GroupedHorizontalBarChartDTO } from './groupedHorizontalBarChartDTO';
import { GroupedVerticalBarChartDTO } from './groupedVerticalBarChartDTO';
import { HeatMapChartDTO } from './heatMapChartDTO';
import { HorizontalBarChartDTO } from './horizontalBarChartDTO';
import { NameValueChartDTO } from './nameValueChartDTO';
import { NormalizedAreaChartDTO } from './normalizedAreaChartDTO';
import { NormalizedHorizontalBarChartDTO } from './normalizedHorizontalBarChartDTO';
import { NormalizedVerticalBarChartDTO } from './normalizedVerticalBarChartDTO';
import { NumberCardChartDTO } from './numberCardChartDTO';
import { PieChartDTO } from './pieChartDTO';
import { PieGridChartDTO } from './pieGridChartDTO';
import { PolarChartDTO } from './polarChartDTO';
import { SeriesChartDTO } from './seriesChartDTO';
import { StackedAreaChartDTO } from './stackedAreaChartDTO';
import { StackedHorizontalBarChartDTO } from './stackedHorizontalBarChartDTO';
import { StackedVerticalBarChartDTO } from './stackedVerticalBarChartDTO';
import { TableChartDTO } from './tableChartDTO';
import { TreeMapChartDTO } from './treeMapChartDTO';
import { VerticalBarChartDTO } from './verticalBarChartDTO';

export interface BootstrapedChartDTO {
    bootstrapClass: Array<BootstrapedChartDTO.BootstrapClassEnum>;
    chartData: AdvancedPieChartDTO
    | AreaChartDTO
    | BoxChartDTO
    | GaugeChartDTO
    | GroupedHorizontalBarChartDTO
    | GroupedVerticalBarChartDTO
    | HeatMapChartDTO
    | HorizontalBarChartDTO
    | NameValueChartDTO
    | NormalizedAreaChartDTO
    | NormalizedHorizontalBarChartDTO
    | NormalizedVerticalBarChartDTO
    | NumberCardChartDTO
    | PieChartDTO
    | PieGridChartDTO
    | PolarChartDTO
    | SeriesChartDTO
    | StackedAreaChartDTO
    | StackedHorizontalBarChartDTO
    | StackedVerticalBarChartDTO
   // | TableChartDTO
    | TreeMapChartDTO
    | VerticalBarChartDTO;
}
export namespace BootstrapedChartDTO {
    export type BootstrapClassEnum = 'col' | 'col_1' | 'col_2' | 'col_3' | 'col_4' | 'col_5' | 'col_6' | 'col_7' | 'col_8' | 'col_9' | 'col_10' | 'col_11' | 'col_12' | 'col_sm_1' | 'col_sm_2' | 'col_sm_3' | 'col_sm_4' | 'col_sm_5' | 'col_sm_6' | 'col_sm_7' | 'col_sm_8' | 'col_sm_9' | 'col_sm_10' | 'col_sm_11' | 'col_sm_12' | 'col_md_1' | 'col_md_2' | 'col_md_3' | 'col_md_4' | 'col_md_5' | 'col_md_6' | 'col_md_7' | 'col_md_8' | 'col_md_9' | 'col_md_10' | 'col_md_11' | 'col_md_12' | 'col_lg_1' | 'col_lg_2' | 'col_lg_3' | 'col_lg_4' | 'col_lg_5' | 'col_lg_6' | 'col_lg_7' | 'col_lg_8' | 'col_lg_9' | 'col_lg_10' | 'col_lg_11' | 'col_lg_12' | 'col_xl_1' | 'col_xl_2' | 'col_xl_3' | 'col_xl_4' | 'col_xl_5' | 'col_xl_6' | 'col_xl_7' | 'col_xl_8' | 'col_xl_9' | 'col_xl_10' | 'col_xl_11' | 'col_xl_12';
    export const BootstrapClassEnum = {
        Col: 'col' as BootstrapClassEnum,
        Col1: 'col_1' as BootstrapClassEnum,
        Col2: 'col_2' as BootstrapClassEnum,
        Col3: 'col_3' as BootstrapClassEnum,
        Col4: 'col_4' as BootstrapClassEnum,
        Col5: 'col_5' as BootstrapClassEnum,
        Col6: 'col_6' as BootstrapClassEnum,
        Col7: 'col_7' as BootstrapClassEnum,
        Col8: 'col_8' as BootstrapClassEnum,
        Col9: 'col_9' as BootstrapClassEnum,
        Col10: 'col_10' as BootstrapClassEnum,
        Col11: 'col_11' as BootstrapClassEnum,
        Col12: 'col_12' as BootstrapClassEnum,
        ColSm1: 'col_sm_1' as BootstrapClassEnum,
        ColSm2: 'col_sm_2' as BootstrapClassEnum,
        ColSm3: 'col_sm_3' as BootstrapClassEnum,
        ColSm4: 'col_sm_4' as BootstrapClassEnum,
        ColSm5: 'col_sm_5' as BootstrapClassEnum,
        ColSm6: 'col_sm_6' as BootstrapClassEnum,
        ColSm7: 'col_sm_7' as BootstrapClassEnum,
        ColSm8: 'col_sm_8' as BootstrapClassEnum,
        ColSm9: 'col_sm_9' as BootstrapClassEnum,
        ColSm10: 'col_sm_10' as BootstrapClassEnum,
        ColSm11: 'col_sm_11' as BootstrapClassEnum,
        ColSm12: 'col_sm_12' as BootstrapClassEnum,
        ColMd1: 'col_md_1' as BootstrapClassEnum,
        ColMd2: 'col_md_2' as BootstrapClassEnum,
        ColMd3: 'col_md_3' as BootstrapClassEnum,
        ColMd4: 'col_md_4' as BootstrapClassEnum,
        ColMd5: 'col_md_5' as BootstrapClassEnum,
        ColMd6: 'col_md_6' as BootstrapClassEnum,
        ColMd7: 'col_md_7' as BootstrapClassEnum,
        ColMd8: 'col_md_8' as BootstrapClassEnum,
        ColMd9: 'col_md_9' as BootstrapClassEnum,
        ColMd10: 'col_md_10' as BootstrapClassEnum,
        ColMd11: 'col_md_11' as BootstrapClassEnum,
        ColMd12: 'col_md_12' as BootstrapClassEnum,
        ColLg1: 'col_lg_1' as BootstrapClassEnum,
        ColLg2: 'col_lg_2' as BootstrapClassEnum,
        ColLg3: 'col_lg_3' as BootstrapClassEnum,
        ColLg4: 'col_lg_4' as BootstrapClassEnum,
        ColLg5: 'col_lg_5' as BootstrapClassEnum,
        ColLg6: 'col_lg_6' as BootstrapClassEnum,
        ColLg7: 'col_lg_7' as BootstrapClassEnum,
        ColLg8: 'col_lg_8' as BootstrapClassEnum,
        ColLg9: 'col_lg_9' as BootstrapClassEnum,
        ColLg10: 'col_lg_10' as BootstrapClassEnum,
        ColLg11: 'col_lg_11' as BootstrapClassEnum,
        ColLg12: 'col_lg_12' as BootstrapClassEnum,
        ColXl1: 'col_xl_1' as BootstrapClassEnum,
        ColXl2: 'col_xl_2' as BootstrapClassEnum,
        ColXl3: 'col_xl_3' as BootstrapClassEnum,
        ColXl4: 'col_xl_4' as BootstrapClassEnum,
        ColXl5: 'col_xl_5' as BootstrapClassEnum,
        ColXl6: 'col_xl_6' as BootstrapClassEnum,
        ColXl7: 'col_xl_7' as BootstrapClassEnum,
        ColXl8: 'col_xl_8' as BootstrapClassEnum,
        ColXl9: 'col_xl_9' as BootstrapClassEnum,
        ColXl10: 'col_xl_10' as BootstrapClassEnum,
        ColXl11: 'col_xl_11' as BootstrapClassEnum,
        ColXl12: 'col_xl_12' as BootstrapClassEnum
    };
}