/**
 * ApiGateway
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *  https://getbootstrap.com/docs/4.0/layout/grid/   +---------------------+--------------------------------------+--------------+---------------+--------------+---------------------+   |                     |          Extra small <576px          | Small ≥576px | Medium ≥768px | Large ≥992px | Extra large ≥1200px |   +---------------------+--------------------------------------+--------------+---------------+--------------+---------------------+   | Max container width | None (auto)                          | 540px        | 720px         | 960px        | 1140px              |   | Class prefix        | .col-                                | .col-sm-     | .col-md-      | .col-lg-     | .col-xl-            |   | # of columns        | 12                                                                                                       |   | Gutter width        | 30px (15px on each side of a column)                                                                     |   | Nestable            | Yes                                                                                                      |   | Column ordering     | Yes                                                                                                      |   +---------------------+--------------------------------------+--------------+---------------+--------------+---------------------+
 */
export type BootstrapClassDTO = 'col' | 'col_1' | 'col_2' | 'col_3' | 'col_4' | 'col_5' | 'col_6' | 'col_7' | 'col_8' | 'col_9' | 'col_10' | 'col_11' | 'col_12' | 'col_sm_1' | 'col_sm_2' | 'col_sm_3' | 'col_sm_4' | 'col_sm_5' | 'col_sm_6' | 'col_sm_7' | 'col_sm_8' | 'col_sm_9' | 'col_sm_10' | 'col_sm_11' | 'col_sm_12' | 'col_md_1' | 'col_md_2' | 'col_md_3' | 'col_md_4' | 'col_md_5' | 'col_md_6' | 'col_md_7' | 'col_md_8' | 'col_md_9' | 'col_md_10' | 'col_md_11' | 'col_md_12' | 'col_lg_1' | 'col_lg_2' | 'col_lg_3' | 'col_lg_4' | 'col_lg_5' | 'col_lg_6' | 'col_lg_7' | 'col_lg_8' | 'col_lg_9' | 'col_lg_10' | 'col_lg_11' | 'col_lg_12' | 'col_xl_1' | 'col_xl_2' | 'col_xl_3' | 'col_xl_4' | 'col_xl_5' | 'col_xl_6' | 'col_xl_7' | 'col_xl_8' | 'col_xl_9' | 'col_xl_10' | 'col_xl_11' | 'col_xl_12';

export const BootstrapClassDTO = {
    Col: 'col' as BootstrapClassDTO,
    Col1: 'col_1' as BootstrapClassDTO,
    Col2: 'col_2' as BootstrapClassDTO,
    Col3: 'col_3' as BootstrapClassDTO,
    Col4: 'col_4' as BootstrapClassDTO,
    Col5: 'col_5' as BootstrapClassDTO,
    Col6: 'col_6' as BootstrapClassDTO,
    Col7: 'col_7' as BootstrapClassDTO,
    Col8: 'col_8' as BootstrapClassDTO,
    Col9: 'col_9' as BootstrapClassDTO,
    Col10: 'col_10' as BootstrapClassDTO,
    Col11: 'col_11' as BootstrapClassDTO,
    Col12: 'col_12' as BootstrapClassDTO,
    ColSm1: 'col_sm_1' as BootstrapClassDTO,
    ColSm2: 'col_sm_2' as BootstrapClassDTO,
    ColSm3: 'col_sm_3' as BootstrapClassDTO,
    ColSm4: 'col_sm_4' as BootstrapClassDTO,
    ColSm5: 'col_sm_5' as BootstrapClassDTO,
    ColSm6: 'col_sm_6' as BootstrapClassDTO,
    ColSm7: 'col_sm_7' as BootstrapClassDTO,
    ColSm8: 'col_sm_8' as BootstrapClassDTO,
    ColSm9: 'col_sm_9' as BootstrapClassDTO,
    ColSm10: 'col_sm_10' as BootstrapClassDTO,
    ColSm11: 'col_sm_11' as BootstrapClassDTO,
    ColSm12: 'col_sm_12' as BootstrapClassDTO,
    ColMd1: 'col_md_1' as BootstrapClassDTO,
    ColMd2: 'col_md_2' as BootstrapClassDTO,
    ColMd3: 'col_md_3' as BootstrapClassDTO,
    ColMd4: 'col_md_4' as BootstrapClassDTO,
    ColMd5: 'col_md_5' as BootstrapClassDTO,
    ColMd6: 'col_md_6' as BootstrapClassDTO,
    ColMd7: 'col_md_7' as BootstrapClassDTO,
    ColMd8: 'col_md_8' as BootstrapClassDTO,
    ColMd9: 'col_md_9' as BootstrapClassDTO,
    ColMd10: 'col_md_10' as BootstrapClassDTO,
    ColMd11: 'col_md_11' as BootstrapClassDTO,
    ColMd12: 'col_md_12' as BootstrapClassDTO,
    ColLg1: 'col_lg_1' as BootstrapClassDTO,
    ColLg2: 'col_lg_2' as BootstrapClassDTO,
    ColLg3: 'col_lg_3' as BootstrapClassDTO,
    ColLg4: 'col_lg_4' as BootstrapClassDTO,
    ColLg5: 'col_lg_5' as BootstrapClassDTO,
    ColLg6: 'col_lg_6' as BootstrapClassDTO,
    ColLg7: 'col_lg_7' as BootstrapClassDTO,
    ColLg8: 'col_lg_8' as BootstrapClassDTO,
    ColLg9: 'col_lg_9' as BootstrapClassDTO,
    ColLg10: 'col_lg_10' as BootstrapClassDTO,
    ColLg11: 'col_lg_11' as BootstrapClassDTO,
    ColLg12: 'col_lg_12' as BootstrapClassDTO,
    ColXl1: 'col_xl_1' as BootstrapClassDTO,
    ColXl2: 'col_xl_2' as BootstrapClassDTO,
    ColXl3: 'col_xl_3' as BootstrapClassDTO,
    ColXl4: 'col_xl_4' as BootstrapClassDTO,
    ColXl5: 'col_xl_5' as BootstrapClassDTO,
    ColXl6: 'col_xl_6' as BootstrapClassDTO,
    ColXl7: 'col_xl_7' as BootstrapClassDTO,
    ColXl8: 'col_xl_8' as BootstrapClassDTO,
    ColXl9: 'col_xl_9' as BootstrapClassDTO,
    ColXl10: 'col_xl_10' as BootstrapClassDTO,
    ColXl11: 'col_xl_11' as BootstrapClassDTO,
    ColXl12: 'col_xl_12' as BootstrapClassDTO
};