/**
 * ApiGateway
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ColorSchemeDTO } from './colorSchemeDTO';

export interface ChartConfigurationDTO { 
    colorScheme: ColorSchemeDTO;
    animations: boolean;
    showLegend: boolean;
    legendTitle: string;
    legendPosition: string;
    xAxisLabel: string;
    yAxisLabel: string;
    showXAxisLabel: boolean;
    showYAxisLabel: boolean;
}