/**
 * ApiGateway
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *  Rework - 2021.11.03
 */
export type ChartTypeDTO =
    'StackedAreaChart'
    | 'AreaChart'
    | 'NormalizedAreaChart'
    | 'LineChart'
    | 'NormalizedHorizontalBarChart'
    | 'StackedVerticalBarChart'
    | 'VerticalBarChart'
    | 'GroupedHorizontalBarChart'
    | 'NormalizedVerticalBarChart'
    | 'StackedHorizontalBarChart'
    | 'GroupedVerticalBarChart'
    | 'HorizontalBarChart'
    | 'PieGridChart'
    | 'AdvancedPieChart'
    | 'PieChart'
    | 'HeatMapChart'
    | 'GaugeChart'
    | 'PolarChart'
    | 'NumberCardChart'
    | 'TreeMapChart'
    | 'BoxChart';

export const ChartTypeDTO = {
    StackedAreaChart: 'StackedAreaChart' as ChartTypeDTO,
    AreaChart: 'AreaChart' as ChartTypeDTO,
    NormalizedAreaChart: 'NormalizedAreaChart' as ChartTypeDTO,
    LineChart: 'LineChart' as ChartTypeDTO,
    NormalizedHorizontalBarChart: 'NormalizedHorizontalBarChart' as ChartTypeDTO,
    StackedVerticalBarChart: 'StackedVerticalBarChart' as ChartTypeDTO,
    VerticalBarChart: 'VerticalBarChart' as ChartTypeDTO,
    GroupedHorizontalBarChart: 'GroupedHorizontalBarChart' as ChartTypeDTO,
    NormalizedVerticalBarChart: 'NormalizedVerticalBarChart' as ChartTypeDTO,
    StackedHorizontalBarChart: 'StackedHorizontalBarChart' as ChartTypeDTO,
    GroupedVerticalBarChart: 'GroupedVerticalBarChart' as ChartTypeDTO,
    HorizontalBarChart: 'HorizontalBarChart' as ChartTypeDTO,
    PieGridChart: 'PieGridChart' as ChartTypeDTO,
    AdvancedPieChart: 'AdvancedPieChart' as ChartTypeDTO,
    PieChart: 'PieChart' as ChartTypeDTO,
    HeatMapChart: 'HeatMapChart' as ChartTypeDTO,
    GaugeChart: 'GaugeChart' as ChartTypeDTO,
    PolarChart: 'PolarChart' as ChartTypeDTO,
    NumberCardChart: 'NumberCardChart' as ChartTypeDTO,
    TreeMapChart: 'TreeMapChart' as ChartTypeDTO,
    BoxChart: 'BoxChart' as ChartTypeDTO,
    TableChart: 'TableChart' as ChartTypeDTO,
};