/**
 * ApiGateway
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type UniqueChartIdDTO = 'PaymentMethods_StackedVerticalChart' | 'PaymentMethods_PieChart' | 'Collectors_StackedVerticalChart' | 'Collectors_PieChart' | 'Discounts_TotalDiscountsInInterval_Chart' | 'Discounts_CompareWithInterval' | 'Discounts_CompareWithInterval_Percentage' | 'Incomes_TotalIncomesInInterval_Chart' | 'Incomes_CompareWithInterval' | 'Incomes_CompareWithInterval_Percentage' | 'ReturnsAndVoids_TotalValueInInterval_Card' | 'ReturnsAndVoids_TotalValueInInterval_Chart' | 'ReturnsAndVoids_OnlyReturnsInInterval' | 'ReturnsAndVoids_OnlyVoidsInInterval' | 'ReturnsAndVoids_CompareWithInterval' | 'ReturnsAndVoids_CompareWithInterval_Percentage' | 'VAT_TotalVATInInterval_Chart' | 'VAT_CompareWithInterval' | 'VAT_CompareWithInterval_Percentage' | 'Custom';

export const UniqueChartIdDTO = {
    PaymentMethodsStackedVerticalChart: 'PaymentMethods_StackedVerticalChart' as UniqueChartIdDTO,
    PaymentMethodsPieChart: 'PaymentMethods_PieChart' as UniqueChartIdDTO,
    CollectorsStackedVerticalChart: 'Collectors_StackedVerticalChart' as UniqueChartIdDTO,
    CollectorsPieChart: 'Collectors_PieChart' as UniqueChartIdDTO,
    DiscountsTotalDiscountsInIntervalChart: 'Discounts_TotalDiscountsInInterval_Chart' as UniqueChartIdDTO,
    DiscountsCompareWithInterval: 'Discounts_CompareWithInterval' as UniqueChartIdDTO,
    DiscountsCompareWithIntervalPercentage: 'Discounts_CompareWithInterval_Percentage' as UniqueChartIdDTO,
    IncomesTotalIncomesInIntervalChart: 'Incomes_TotalIncomesInInterval_Chart' as UniqueChartIdDTO,
    IncomesCompareWithInterval: 'Incomes_CompareWithInterval' as UniqueChartIdDTO,
    IncomesCompareWithIntervalPercentage: 'Incomes_CompareWithInterval_Percentage' as UniqueChartIdDTO,
    ReturnsAndVoidsTotalValueInIntervalCard: 'ReturnsAndVoids_TotalValueInInterval_Card' as UniqueChartIdDTO,
    ReturnsAndVoidsTotalValueInIntervalChart: 'ReturnsAndVoids_TotalValueInInterval_Chart' as UniqueChartIdDTO,
    ReturnsAndVoidsOnlyReturnsInInterval: 'ReturnsAndVoids_OnlyReturnsInInterval' as UniqueChartIdDTO,
    ReturnsAndVoidsOnlyVoidsInInterval: 'ReturnsAndVoids_OnlyVoidsInInterval' as UniqueChartIdDTO,
    ReturnsAndVoidsCompareWithInterval: 'ReturnsAndVoids_CompareWithInterval' as UniqueChartIdDTO,
    ReturnsAndVoidsCompareWithIntervalPercentage: 'ReturnsAndVoids_CompareWithInterval_Percentage' as UniqueChartIdDTO,
    VATTotalVATInIntervalChart: 'VAT_TotalVATInInterval_Chart' as UniqueChartIdDTO,
    VATCompareWithInterval: 'VAT_CompareWithInterval' as UniqueChartIdDTO,
    VATCompareWithIntervalPercentage: 'VAT_CompareWithInterval_Percentage' as UniqueChartIdDTO,
    Custom: 'Custom' as UniqueChartIdDTO
};